import { useState } from 'react';

type Pct = { vmid: number; status: string; name: string; address?: string; docker?: boolean; collector?: boolean };
export function EnrollmentPanel({ onChanged }: { onChanged: () => void }) {
  const [open, setOpen] = useState(false), [loading, setLoading] = useState(false), [items, setItems] = useState<Pct[]>([]), [error, setError] = useState('');
  const discover = async () => { setOpen(true); setLoading(true); setError(''); try { const response = await fetch('/api/v1/enrollment/discover'); if (!response.ok) throw new Error((await response.json()).error ?? `HTTP ${response.status}`); setItems(await response.json()); } catch (e) { setError(e instanceof Error ? e.message : 'Discovery failed'); } finally { setLoading(false); } };
  const enroll = async (item: Pct) => { const phrase = `ENROLL PCT ${item.vmid}`, confirmation = window.prompt(`This installs the restricted Atlas collector in PCT ${item.vmid}. Type ${phrase} to continue.`); if (confirmation !== phrase) return; setLoading(true); setError(''); try { const response = await fetch('/api/v1/enrollment/enroll', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ vmid: item.vmid, confirmation }) }); if (!response.ok) throw new Error((await response.json()).error ?? `HTTP ${response.status}`); await discover(); onChanged(); } catch (e) { setError(e instanceof Error ? e.message : 'Enrollment failed'); setLoading(false); } };
  return <><button className="discover-button" onClick={() => void discover()} disabled={loading}>{loading ? 'Discovering…' : 'Discover PCTs'}</button>{open && <div className="enrollment-panel"><div className="panel-head"><h2>PCT discovery</h2><button onClick={() => setOpen(false)}>Close</button></div>{error && <div className="banner">{error}</div>}<div className="enrollment-list">{items.map(item => <div key={item.vmid}><b>PCT {item.vmid}</b><span><strong>{item.name}</strong><small>{item.status} · {item.address ?? 'address unavailable'}</small></span>{item.collector ? <em>Enrolled</em> : <button disabled={item.status !== 'running' || loading} onClick={() => void enroll(item)}>Enroll collector</button>}</div>)}</div></div>}</>;
}
